{
	"version": 1739772421,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/crosshair-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/bullseye-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/imagephotoroom20250217t-sheet0.png",
		"images/image_fx_photoroom-sheet0.png",
		"images/b1-sheet0.png",
		"media/bgm - meme mash.m4a",
		"media/bgm - meme mash.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"stop it.mp4",
		"omg.mp4",
		"yeah boi.mp4",
		"jk simmons.mp4",
		"spanish guy laugh.mp4",
		"nice.mp4"
	]
}